#!/bin/sh
echo "ProxyChains-4.0 (http://proxychains.sf.net)"

usage() {

	echo "	usage:"
	echo "		$0 [h] [f config-file] <prog> [args]"
	exit
}

if [ $# = 0 ] ; then
	usage
fi

if [ $1 = "-h" ]; then
	usage
fi

if [ "$1" = "-f" ]; then
	export PROXYCHAINS_CONF_FILE=$2;
	shift;
	shift;
fi

if [ $(uname) = "Darwin" ]; then
	export DYLD_FORCE_FLAT_NAMESPACE=
	export DYLD_INSERT_LIBRARIES=libproxychains4.dylib
else
	export LD_PRELOAD=libproxychains.so.4
fi
exec "$@"
